urdb/config/routes.rb
Urdb::Application.routes.draw do
  root 'movies#index'
  # get '/movies' => 'movies#index'

  get '/movies/:id' => 'movies#show', as: 'movie'
 end

urdb/app/models/movie.rb
class Movie < ActiveRecord::Base
end

urdb/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

urdb/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  
  def index
    @movies = Movie.all
  end

  def show
    id = params[:id]
    @movie = Movie.find(id)
  end

end

urdb/app/helpers/application_helper.rb
module ApplicationHelper
end

urdb/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Urdb</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

urdb/app/views/movies/index.html.erb
<h1> Movies: </h1>

<% @movies.each do |movie| %>
	<li><%= link_to movie.title, movie_path(movie.id) %></li>
<% end %>

urdb/app/views/movies/show.html.erb
<%= @movies %>
<h1><%= @movie.title %></h1>
<li><%= @movie.description %></li>
<img src = "<%= @movie.gif %>" height=250>

<iframe width="560" height="315" src="<%= @movie.trailer%>" frameborder="0" allowfullscreen></iframe>

<p><a href = "/"> Back to main page </a></p>